### ISSUE TITLE
Model with default `setup` method and `weights` file/directory crashes on boot

### ISSUE THREAD

**Issue by nickstenning** [replicate/cog#1055]
The `tencentarc/animesr` model ran into an issue where it was crashing on setup with

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 185, in _setup
run_setup(self._predictor)
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/predictor.py", line 75, in run_setup
raise ValueError(
ValueError: Predictor.setup() has an argument 'weights' of type typing.Union[cog.types.File, cog.types.Path, NoneType], but only File and Path are supported
```

The model is not trainable, and does not accept magic weights inputs. The issue appears to occur because of [this piece of code](https://github.com/replicate/cog/blob/cf6a49b46126fbeb7e82ab2c35fb9b4273c8afcf/python/cog/predictor.py#L70-L77), which we hit when:

1. The model doesn't define its own `setup` which means that it uses `BasePredictor.setup` (which defines the type of `weights` as `Optional[Union[CogFile, CogPath]]`.
2. It has a file on disk at `weights` (see [here](https://github.com/replicate/cog/blob/cf6a49b46126fbeb7e82ab2c35fb9b4273c8afcf/python/cog/predictor.py#L55)) which triggers this validation behaviour.

We should probably either remove the default `weights` parameter from `BasePredictor.setup`, or make the typechecking in the validation code handle `Optional`/`Union` etc. correctly.

**Comment by anish-sahoo** [comment]
Closing because BaseRunner.setup now accepts weights as Optional[Union[Path, str]], resolving the boot crash.
