### ISSUE TITLE
ability to get into defunct state?

### ISSUE THREAD

**Issue by anotherjesse** [replicate/cog#1090]
We are seeing models periodically get into an error state:

```
error                     | Invalid operation: state is WorkerState.DEFUNCT (must be WorkerState.READY)
run_logs                  | Traceback (most recent call last):                                                                                                                +
                          |   File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/runner.py", line 334, in predict                                      +
                          |     return _predict(                                                                                                                              +
                          |   File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/runner.py", line 370, in _predict                                     +
                          |     for event in worker.predict(input_dict, poll=0.1):                                                                                            +
                          |   File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/worker.py", line 63, in predict                                       +
                          |     self._assert_state(WorkerState.READY)                                                                                                         +
                          |   File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/worker.py", line 97, in _assert_state                                 +
                          |     raise InvalidStateException(                                                                                                                  +
                          | cog.server.exceptions.InvalidStateException: Invalid operation: state is WorkerState.DEFUNCT (must be WorkerState.READY)
```

We see it often on models that have less than stellar error handling..

(For example, prints the error from a core section of the prediction and then continues on as if it isn't important.)

```
            except RuntimeError as error:
                print(error)
```

To find a repro, perhaps looking at what happens when various types of exceptions occur?

**Comment by sadir876** [comment]
![Uploading BTTTTT.png…]()
