### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by mad-wizard** [replicate/cog#1242]
Experiencing this error both on Mac and Linux, attempting to get 

Full stack trace:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.17/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/.pyenv/versions/3.8.17/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/.pyenv/versions/3.8.17/lib/python3.8/site-packages/cog/__init__.py", line 1, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform

ⅹ Failed to get type signature: exit status 1
```

I'm aware that this issue has already been mentioned just wanted to note it is not OS specific and seems to be some kind of package problem with cog itself.

**Comment by mad-wizard** [comment]
For anyone else who has this problem, I resolved it by downgrading pydantic as such ```"pydantic==1.10.1"```

You may need to also change other package versions to accommodate this.
