### ISSUE TITLE
How to gracefully return back with no img output 

### ISSUE THREAD

**Issue by jerry275** [replicate/cog#1386]
In below code snippet, how can I gracefully mark the prediction as completed with some custom output when "No human detected in the image!"

```
def predict(
        self,
        image: Path = Input(description="Grayscale input image"),
        scale: float = Input(
            description="Factor to scale image by", ge=0, le=10, default=1.5
        ),
    ) -> List[Path]:
        """Run a single prediction on the model"""
        # processed_input = preprocess(image)
        # output = self.model(processed_image, scale)
        # Create the full input path and read the file

        img = Image.open(image)

        image_extension = image.suffix
        print("Image extension:", image_extension)

        image_np = np.array(img)

        if image_np is None:
            return
        height, width, _ = image_np.shape

        # Assign the image bounds to c1, c2, d1, d2
        c1, c2, d1, d2 = 0, 0, width, height

        # Run the image through the model
        results = model(img)

        output = []
        # Find the first human detected in the image
        human = next((x for x in results.xyxy[0] if int(x[5]) == 0), None)

        if human is None:
            print("No human detected in the image!")
            return
```
I am getting below error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14afe4c]

goroutine 1 [running]:
github.com/replicate/cog/pkg/cli.handleMultipleFileOutput(0x1528ae0?, 0xc0002c7f20?)
	/home/runner/work/cog/cog/pkg/cli/predict.go:256 +0x2c
github.com/replicate/cog/pkg/cli.predictIndividualInputs({{{0x0, 0x0, 0x0}, {0xc000098770, 0x1, 0x1}, {0x0, 0x0}, {0xc000299c10, 0xd}, ...}, ...}, ...)
	/home/runner/work/cog/cog/pkg/cli/predict.go:180 +0x1dc
github.com/replicate/cog/pkg/cli.cmdPredict(0xc00029cf00?, {0xc00025b540?, 0x2?, 0x2?})
	/home/runner/work/cog/cog/pkg/cli/predict.go:153 +0x9be
github.com/spf13/cobra.(*Command).execute(0xc00029cf00, {0xc00025b520, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00029c000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x199d420?)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	/home/runner/work/cog/cog/cmd/cog/cog.go:14 +0x6f
```

**Comment by mattt** [comment]
Hi @jerry275. Your bare `return` in the `if human is None` condition has the effect of returning `None`. Try changing that to `return []` instead.

**Comment by yorickvP** [comment]
Looks like this is cog v0.8.6. The error message here should be improved.

**Comment by markphelps** [comment]
This issue has been inactive for over two years. The immediate workaround is to return an empty list `[]` rather than `None` when no output files are produced. While the underlying nil-pointer panic in `handleMultipleFileOutput` is a real bug, there is a known workaround and no recent activity. Closing as stale. If this crash is still reproducible on the latest version of Cog, please open a new issue with updated details.
