### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by alexanderliu-creator** [replicate/cog#1463]
When I'm executing the resnet cog demo at [here](https://github.com/replicate/cog-examples/tree/main/resnet), I find a problem when executing the "cog build" command, the error is:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/cog/__init__.py", line 1, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform

ⅹ Failed to get type signature: exit status 1

**Comment by lucataco** [comment]
At this time pydantic version above 2 conflicts with cog, please set a version lower to run it
