### ISSUE TITLE
HTTPX verifytypes error

### ISSUE THREAD

**Issue by christopher5106** [replicate/cog#2079]
During cog push in our CI, we get the following error:

```
Validating model schema...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/cog/command/openapi_schema.py", line 12, in <module>
    from ..server.http import create_app
  File "/usr/local/lib/python3.12/site-packages/cog/server/http.py", line 47, in <module>
    from .runner import (
  File "/usr/local/lib/python3.12/site-packages/cog/server/runner.py", line 21, in <module>
    from .clients import SKIP_START_EVENT, ClientManager
  File "/usr/local/lib/python3.12/site-packages/cog/server/clients.py", line 27, in <module>
    from .retry_transport import RetryTransport
  File "/usr/local/lib/python3.12/site-packages/cog/server/retry_transport.py", line 11, in <module>
    class RetryTransport(httpx.AsyncBaseTransport):
  File "/usr/local/lib/python3.12/site-packages/cog/server/retry_transport.py", line 35, in RetryTransport
    verify: httpx._types.VerifyTypes = True,
            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpx._types' has no attribute 'VerifyTypes'. Did you mean: 'ProxyTypes'?

ⅹ Failed to get type signature: exit status 1
```

Cog setup is:
```

     - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          cog-version: "v0.10.0-alpha21"
          token: ${{ secrets.REPLICATE_API_TOKEN }}
```

**Comment by meatballhat** [comment]
This looks like `httpx>=0.28` must be present since `0.28.0` includes the removal of `VerifyTypes`. If you can upgrade to `v0.10.0a27` this error should resolve since that release restricts the `httpx` dependency so that this won't happen.
