### ISSUE TITLE
Tell users to upgrade if they use @cog.input() with new Cog

### ISSUE THREAD

**Issue by zeke** [replicate/cog#427]
If a user of ["new cog"](https://github.com/replicate/cog/pull/407) (>=0.1.0) tries to `cog push` a model implemented in "old cog", they'll get an error like this:

```
$ cog push
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/cog/command/openapi_schema.py", line 18, in <module>
    predictor = load_predictor()
  File "/usr/local/lib/python3.9/site-packages/cog/predictor.py", line 68, in load_predictor
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "predict.py", line 6, in <module>
    class Predictor(cog.Predictor):
  File "predict.py", line 10, in Predictor
    @cog.input("username", type=str, help="GitHub username")
AttributeError: module 'cog' has no attribute 'input'

ⅹ Failed to get type signature: exit status 1
```

Let's update new cog to catch this and give users some guidance.

**Comment by theotherjenkutler** [comment]
I have the same issue

```Adding labels to image...

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/cog/command/openapi_schema.py", line 26, in <module>
    app = create_app(predictor_ref)
  File "/usr/local/lib/python3.7/site-packages/cog/server/http.py", line 46, in create_app
    predictor = load_predictor_from_ref(predictor_ref)
  File "/usr/local/lib/python3.7/site-packages/cog/predictor.py", line 91, in load_predictor_from_ref
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "predict.py", line 27, in <module>
    class Predictor(cog.Predictor):
AttributeError: module 'cog' has no attribute 'Predictor'

ⅹ Failed to get type signature: exit status 1
```

**Comment by gonewiththeway** [comment]
Hello, I have the same issue. Is there an update to this, please?

**Comment by gonewiththeway** [comment]
I was able to fix it by updating according to [this](https://github.com/replicate/cog/pull/407) 

1. Update Predictor class to subclass from BasePredictor
2. Update input method `predict` to new style instead of annotations.

cc: @theotherjenkutler
