### ISSUE TITLE
Update pydantic Cog to serialize pathlib Paths

### ISSUE THREAD

**Issue by zeke** [replicate/cog#444]
TypeError: Object of type PosixPath is not JSON serializable

See https://stackoverflow.com/questions/70183853/send-pathlib-path-data-to-fastapi-posixpath-is-not-json-serializable

```
{'_state': <django.db.models.base.ModelState object at 0xffff868e2170>,
'id': 1534167,
'uuid': 'okycwtwlsrge7b6vgcnfjnxwze',
'version_id': 3660,
'user_id': 50,
'is_shared': False,
'created_at': datetime.datetime(2022, 2, 25, 15, 43, 49, 544262, tzinfo=datetime.timezone.utc),
'status_preparing_at': datetime.datetime(2022, 2, 25, 15, 43, 50, 187300, tzinfo=datetime.timezone.utc),
'status_queued_at': datetime.datetime(2022, 2, 25, 15, 43, 50, 187316, tzinfo=datetime.timezone.utc),
'status_processing_at': datetime.datetime(2022, 2, 25, 15, 43, 50, 187320, tzinfo=datetime.timezone.utc),
'status_cancelled_at': None,
'updated_at': datetime.datetime(2022, 2, 25, 15, 43, 50, 187541, tzinfo=datetime.timezone.utc),
'completed_at': datetime.datetime(2022, 2, 25, 15, 43, 50, 187323, tzinfo=datetime.timezone.utc),
'status': 'failed',
'inputs': {},
'output': None,
'output_text': None,
'output_file_id': None,
'serving_id': '25blmzjDkU7Xr6hvHOzZFeOzxUv',
'run_logs': 'Traceback (most recent call last):\n'
            '  File '
            '"/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", '
            'line 164, in start\n'
            '    self.handle_message(response_queue, message, '
            'cleanup_functions)\n'
            '  File '
            '"/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", '
            'line 243, in handle_message\n'
            '    self.push_result(response_queue, return_value, '
            'status="success")\n'
            '  File '
            '"/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", '
            'line 268, in push_result\n'
            '    self.redis.rpush(response_queue, json.dumps(message))\n'
            '  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in '
            'dumps\n'
            '    return _default_encoder.encode(obj)\n'
            '  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in '
            'encode\n'
            '    chunks = self.iterencode(o, _one_shot=True)\n'
            '  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in '
            'iterencode\n'
            '    return _iterencode(o, 0)\n'
            '  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in '
            'default\n'
            "    raise TypeError(f'Object of type {o.__class__.__name__} '\n"
            'TypeError: Object of type PosixPath is not JSON serializable\n',
'error': 'Object of type PosixPath is not JSON serializable',
'anonymous_id': 'f0d78b36-6fe4-4a52-a9de-afe553f2c786',
'ip_address': '172.18.0.1',
'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
              'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 '
              'Safari/537.36'}

```

**Comment by bfirsh** [comment]
You're probably returning `pathlib.Path` instead of `cog.Path`. This is currently undefined behavior.

We need to figure out how best to handle that (whether it's possible to allow it, or whether we throw a more helpful error). See "Future" in https://github.com/replicate/cog/pull/407.

**Comment by zeke** [comment]
> You're probably returning `pathlib.Path` instead of `cog.Path`

Ah yeah that's probably it. I set the annotation properly but not the actual return value.

https://github.com/zeke/cog-haiku/blob/f0cb00f1843e55b91239b28967c497fde4e7da48/predict.py#L60-L62

That reminds me: `cog.Path` is not documented yet. I opened https://github.com/replicate/cog/issues/445 and added it to the list in https://github.com/replicate/cog/pull/407

**Comment by zeke** [comment]
Operator error. Closing. See https://github.com/replicate/cog/issues/445 for updates related to this.
