### ISSUE TITLE
Bad error message from some unallowed input types

### ISSUE THREAD

**Issue by evilstreak** [replicate/cog#597]
Using `Any` or `List[SomeObject]` as an input type makes Cog throw an error when, ironically, it's trying to produce a human readable typename for the bad type:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cog/command/openapi_schema.py", line 24, in <module>
    app = create_app(predictor)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cog/server/http.py", line 34, in create_app
    InputType = get_input_type(predictor)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cog/predictor.py", line 126, in get_input_type
    f"Unsupported input type {human_readable_type_name(InputType)} for parameter `{name}`. Supported input types are: {readable_types_list(ALLOWED_INPUT_TYPES)}."
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cog/predictor.py", line 215, in human_readable_type_name
    return module + "." + t.__qualname__
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __qualname__
```

**Comment by TommyDew42** [comment]
Hi! It looks like a good issue I can help.

Would be happy if I can work on it!

**Comment by bfirsh** [comment]
Thanks again for this @TommyDew42!
