### ISSUE TITLE
Specifying an unsupported CUDA version generates a cryptic error

### ISSUE THREAD

**Issue by evilstreak** [replicate/cog#607]
If you specify a version of CUDA in `cog.yaml` that doesn't exist in `pkg/config/cuda_base_image_tags.json` then `cog build` fails with a pretty cryptic error message:

```
$ cog build
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/replicate/cog/pkg/config.latestCuDNNForCUDA({0x14000213958, 0x6})
        /Users/dominicbaggott/replicate/cog/pkg/config/compatibility.go:204 +0x108
github.com/replicate/cog/pkg/config.(*Config).validateAndCompleteCUDA(0x140001cf7d0)
        /Users/dominicbaggott/replicate/cog/pkg/config/config.go:274 +0xa1c
github.com/replicate/cog/pkg/config.(*Config).ValidateAndCompleteConfig(0x140001cf7d0)
        /Users/dominicbaggott/replicate/cog/pkg/config/config.go:134 +0xb8
github.com/replicate/cog/pkg/config.GetConfig({0x0, 0x0})
        /Users/dominicbaggott/replicate/cog/pkg/config/load.go:46 +0xe0
github.com/replicate/cog/pkg/cli.buildCommand(0x140001f3900, {0x104bf57b0, 0x0, 0x0})
        /Users/dominicbaggott/replicate/cog/pkg/cli/build.go:28 +0x38
github.com/spf13/cobra.(*Command).execute(0x140001f3900, {0x104bf57b0, 0x0, 0x0})
        /Users/dominicbaggott/.go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140001f3680)
        /Users/dominicbaggott/.go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dominicbaggott/.go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /Users/dominicbaggott/replicate/cog/cmd/cog/cog.go:14 +0x94
```

The right response here is to change the version of CUDA you're specifying to one that's supported. We should handle this error more gracefully, and show a useful message to the user with that instruction.

I found this when trying to build a model that specified `cuda: "11.1"`, which used to be a supported version until b057e19.

Here's a minimal `cog.yaml` to reproduce:

```yaml
build:
  gpu: true
  cuda: "11.1"
  python_version: "3.8"
predict: "predict.py:Predictor"
```

**Comment by bfirsh** [comment]
Ah. `11.1` should also probably work, and resolve to latest patch version.

A lot of these issues, and things like #489, make me think we might want to step back and see if we can come up with a more robust overall design.

**Comment by anish-sahoo** [comment]
Closing as latestCuDNNForCUDA now returns a clean error for unsupported CUDA versions instead of panicking.
