### ISSUE TITLE
Scaling Broke, Queue Not Working, Cog 0.44 -> 0.6.1, Latest Stable

### ISSUE THREAD

**Issue by andyprevalsky** [replicate/cog#925]
I am getting this error, 
```ERROR: Exception in ASGI application```
Last Line in Trace ```line 30, in predict assert not self.is_busy()```

in my google cloud run logs after updating my cog version which broke my whole pipeline.

Before I could call the deployed cog build as many times as I wanted, and it would behave like a queue, google cloud build would just scale when the concurrent requests would reach 50.
Now it looks like cog throws an error anytime 2 requests are alive for the same instance. This implies the queue is broken. For some reason.

I changed nothing about my build process other then updating Cog from 0.4.4 to the newest version and also updating my docker to the next stable version. Everything is in a virtual env, no dependencies changed and all are pinned.

```yaml
# cog.yaml
build:
  gpu: false
  python_version: "3.8"
  python_packages:
    - "transformers==4.24.0"
    - "torch==1.13.0"
predict: "predict.py:Predictor"
```

```python
# predict.py
from cog import BasePredictor, Input
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn.functional as F

class Predictor(BasePredictor):
    def setup(self):
        """Load the model into memory to make running multiple predictions efficient"""
        self.model = AutoModelForSequenceClassification.from_pretrained('./transformer', local_files_only=True)
        self.tokenizer = AutoTokenizer.from_pretrained('./transformer', local_files_only=True)

    # The arguments and types the model takes as input
    def predict(self,
          text: str = Input(description="Instagram Bio Information")
    ) -> object:
        """Run a single prediction on the model"""
        tokenized_val_text = self.tokenizer(
            text, 
            truncation=True,
            padding="max_length",
            return_tensors="pt"
        )
        logits = self.model(**tokenized_val_text)['logits']
        prediction = F.softmax(logits, dim=1)
        print(prediction)
        print(prediction.detach().numpy())
        return {
            'prediction': prediction.detach().numpy(),
        }
```

Full Trace
```
Traceback (most recent call last): 
File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi result = await app( # type: ignore[func-returns-value] File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__ raise exc File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__ raise exc File "/usr/local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__ raise e File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app response = await func(request) File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app raw_response = await run_endpoint_function( File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function return await run_in_threadpool(dependant.call, **values) File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool return await anyio.to_thread.run_sync(func, *args) File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run result = context.run(func, *args) File "/usr/local/lib/python3.8/site-packages/cog/server/http.py", line 94, in predict generic_response = runner.predict(request).get() File "/usr/local/lib/python3.8/site-packages/cog/server/runner.py", line 30, in predict assert not self.is_busy()
```

I really need help, feels like cog is just permanently broken until someone realizes this is an issue. Please Help!!!! Thank you!!!!

**Comment by nickstenning** [comment]
Hi @andyprevalsky, it sounds like with Cog 0.4.4 you were effectively using the inbound network socket as a queue. Cog's HTTP interface has no built-in queue.

We're in the process of evolving Cog's HTTP API to allow additional features like cancelation, which requires that we make the HTTP API able to handle other requests while running a prediction. That means that we can't preserve the behaviour where you can throw multiple requests at it and they'll all queue up in the kernel and be executed one by one.

If you're relying on that behaviour, your only option right now will be to downgrade back to pre-v0.6 Cog.

All that said, I'd love to hear more about your setup, and how we can improve on the Cog API for your use case. I can see that it might be convenient in some circumstances to use Cog without an external queue, and we might be able to do some thinking in this issue about how to do that.
