### ISSUE TITLE
Prediction failed for an unknown reason. It might have run out of memory? (exitcode 2)

### ISSUE THREAD

**Issue by cudanexus** [replicate/cog#960]
When running locally the `cog predict -i ` it working fine but when pushed on replicate it giving this error 
`Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/runner.py", line 334, in predict
    return _predict(
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/runner.py", line 370, in _predict
    for event in worker.predict(input_dict, poll=0.1):
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/worker.py", line 135, in _wait
    raise FatalWorkerException(
cog.server.exceptions.FatalWorkerException: Prediction failed for an unknown reason. It might have run out of memory? (exitcode 2)
` any idea @anotherjesse  @bfirsh

**Comment by arnavmehta7** [comment]
Same issue 🤔

**Comment by Tariqh23** [comment]
@anotherjesse @bfirsh

**Comment by arnavmehta7** [comment]
No solution

**Comment by isaacjoy97** [comment]
+1

**Comment by mattt** [comment]
Hi @cudanexus. Can you please share the name of the model on Replicate?

**Comment by AnushreeBannadabhavi** [comment]
+1

**Comment by mattt** [comment]
@AnushreeBannadabhavi @wolfpixels @arnavmehta7 @Tariqh23 If you're seeing the same behavior, could you please share the name of the Replicate model you're using?

**Comment by Muhammadfawad267** [comment]
> When running locally the `cog predict -i ` it working fine but when pushed on replicate it giving this error `Traceback (most recent call last): File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/runner.py", line 334, in predict return _predict( File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/runner.py", line 370, in _predict for event in worker.predict(input_dict, poll=0.1): File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/worker.py", line 135, in _wait raise FatalWorkerException( cog.server.exceptions.FatalWorkerException: Prediction failed for an unknown reason. It might have run out of memory? (exitcode 2) ` any idea @anotherjesse @bfirsh

**Comment by ZYLIM0702** [comment]
do you get the solution. Can you share with me ? Looking forward. Thanks

**Comment by makaronide** [comment]
https://replicate.com/findix/sd-scripts
@mattt The error occurs on this model.

**Comment by Archcollege** [comment]
i have the same problem.https://replicate.com/archcollege/voice

**Comment by notedit** [comment]
same here，when i run  cog predict in local.

**Comment by quocanh34** [comment]
Anyone has the solutions?

**Comment by notedit** [comment]
I came to this and fix it,  maybe your predict func came to some exception that does not be catched.

**Comment by arnavmehta7** [comment]
I've not worked on cog from a lot of time, but this might help someone:

I was able to run it locally as I had better configurations locally than the VM on which I was trying to deploy.
I will suggest reducing the model size or increasing the memory of the machine on which you are trying to deploy.

Additionally try to add a try-except block and do following everywhere in the exception block:
```py
import traceback
print(traceback.format_exc())
```

**Comment by Chyrets** [comment]
has anyone solved the problem?

**Comment by emcmanus** [comment]
Try deploying on more powerful hardware. At least in my case, Cog really did run out of memory.

**Comment by zhangp365** [comment]
I experience the bug:

A bug where a container was unexpectedly killed.

The container started, and the setup was normal. When processing a request, the following error occurred:

```
2025-05-09 02:41:11,643 - INFO - 266 - Generating image with use_zero_init=True...
<PIL.Image.Image image mode=RGB size=1024x1536 at 0x732352132B50>
<PIL.Image.Image image mode=RGB size=512x768 at 0x732354B92DD0> 
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/cog/server/runner.py", line 474, in _handle_done
    f.result()
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cog.server.exceptions.FatalWorkerException: Prediction failed for an unknown reason. It might have run out of memory? (exitcode -6)
```
After repeated comparisons and investigation, I added logs in the running code. On the third attempt, when running again, I noticed that before the process was killed, the following logs were printed:
```
2025-05-09 03:36:10,761 - INFO - 447 - after randn_tensor, noise_latents: torch.Size([1, 16, 64, 64])
2025-05-09 03:36:10,762 - INFO - 458 - after resize_position_encoding, noise_latent_image_ids: torch.Size([1024, 3]), cond_latent_image_ids: torch.Size([1024, 3])
**Could not load symbol cudnnGetLibConfig. Error: /usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9: undefined symbol: cudnnGetLibConfig**
{"prediction_id": null, "logger": "cog.server.runner", "timestamp": "2025-05-09T03:36:10.966484Z", "exception": "Traceback (most recent call last):\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/cog/server/runner.py\", line 474, in _handle_done\n    f.result()\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\ncog.server.exceptions.FatalWorkerException: Prediction failed for an unknown reason. It might have run out of memory? (exitcode -6)", "severity": "ERROR", "message": "caught exception while running predict"}
{"prediction_id": null, "error": "Prediction failed for an unknown reason. It might have run out of memory? (exitcode -6)", "logger": "cog.server.runner", "timestamp": "2025-05-09T03:36:10.967387Z", "severity": "INFO", "message": "prediction failed"}
{"logger": "cog.server.http", "timestamp": "2025-05-09T03:36:10.967738Z", "exception": "Traceback (most recent call last):\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/cog/server/runner.py\", line 474, in _handle_done\n    f.result()\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.11.10/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\ncog.server.exceptions.FatalWorkerException: Prediction failed for an unknown reason. It might have run out of memory? (exitcode -6)", "severity": "ERROR", "message": "encountered fatal error"}
```
There is a log in above log
```
Could not load symbol cudnnGetLibConfig. Error: /usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9: undefined symbol: cudnnGetLibConfig
```
I asked ChatGPT about this error, and it identified the issue as a cuDNN mismatch. It suggested the following check:

```
import torch
print(torch.backends.cudnn.version())
print(torch.backends.cudnn.is_available())
```
At this point, it was clear that PyTorch's cuDNN was mismatched.

I checked the torch version: 2.7.0, and downgraded it to:


- "torch==2.6.0"
- "torchvision==0.21"
After running again, it worked fine.

Therefore, the log message It might have run out of memory is very misleading!
