### ISSUE TITLE
cog python -- NIL go lang error 

### ISSUE THREAD

**Issue by hiwaveSupport** [replicate/cog#964]
`=== GENERATED SEQUENCE 1 ===
['ive heard marvel movies', 0]
i love : ive heard marvel movies
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86d5db]

goroutine 1 [running]:
github.com/replicate/cog/pkg/cli.predictIndividualInputs({{{0x0, 0x0, 0x0}, {0xc00025b7f0, 0x1, 0x1}, {0x945d3d, 0x3}, {0xc00002b1e8, 0x17}, ...}, ...}, ...)
	/home/runner/work/cog/cog/pkg/cli/predict.go:179 +0x41b
github.com/replicate/cog/pkg/cli.cmdPredict(0xc000230c00?, {0xc0001e7580?, 0x4?, 0x4?})
	/home/runner/work/cog/cog/pkg/cli/predict.go:135 +0x6fe
github.com/spf13/cobra.(*Command).execute(0xc000230c00, {0xc0001e7540, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000230000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/runner/work/cog/cog/cmd/cog/cog.go:14 +0x6f
`

I am running text generation as part of a cog image.
Commands:
cog build
cog predict -i xxxx xxxx
The predict code works, loads all the models needed.
Runs the inference.
However, as part of decode and printing the generated text,
COG code runs into NIL condition which exits the code without completing.

Outside of COG container, when I run the same code, no issues.

Any suggestions on how to handle or what might be causing this error?
I am trying to catch all exceptions which make sense  - except (MemoryError, EOFError, IndexError, RuntimeError, Exception) as e: but of course this is outside scope of python.

YAML File:
`# Configuration for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/yaml.md

build:
  # python version in the form '3.8' or '3.8.12'
  python_version: "3.8"
  gpu: true

  # a list of ubuntu apt packages to install
  system_packages:
    - "build-essential"

  python_packages:
    #- "torch==1.8.1"
    - "torch"
    - "transformers"
    - "numpy"
    - "pandas"

  pre_install:
    - "mkdir /src"
    - "pip install git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git"
    #- "git clone git@bitbucket.org:communitycluster/text_generation.git /src/"
    #- "wget xxxxxx"
    #- "unzip xxxxxx.zip -d /src/text_generation/models/"

# predict.py defines how predictions are run on your model
predict: "predict.py:Predictor"
`

OS: Ubuntu 22

**Comment by hiwaveSupport** [comment]
Update: now the model does not even run. I am getting NIL pointer as part of setting up env.
`File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 538, in http_get
for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/requests/models.py", line 822, in generate
raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading pytorch_model.bin:  17%|█▋        | 241M/1.42G [00:15<01:14, 15.9MB/s]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86d5db]

goroutine 1 [running]:
github.com/replicate/cog/pkg/cli.predictIndividualInputs({{{0x0, 0x0, 0x0}, {0xc0003f31d0, 0x1, 0x1}, {0x945d3d, 0x3}, {0xc000155068, 0x17}, ...}, ...}, ...)
	/home/runner/work/cog/cog/pkg/cli/predict.go:179 +0x41b
github.com/replicate/cog/pkg/cli.cmdPredict(0xc00025cc00?, {0xc000199580?, 0x4?, 0x4?})
	/home/runner/work/cog/cog/pkg/cli/predict.go:135 +0x6fe
github.com/spf13/cobra.(*Command).execute(0xc00025cc00, {0xc000199540, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025c000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/runner/work/cog/cog/cmd/cog/cog.go:14 +0x6f
`

**Comment by mattt** [comment]
Hi @hiwaveSupport. From the last call stack you shared, I think the problem has to do with this line:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
```

Could you please update to the latest version of Cog ([v0.8.0-beta6](https://github.com/replicate/cog/releases/tag/v0.8.0-beta6)) and let me know if you're still seeing this error? You might also consider updating to Python 3.11 to see if that helps.

If updating doesn't help, could you share a link to the source code for your model?
