### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/src/cog.yaml'  in built container

### ISSUE THREAD

**Issue by Tenfleques** [replicate/cog#994]
Seems like cog is not copying the directory contents.
when I run the deployed image it fails with the error: Could not find /src/cog.yaml but during the build process there's a clear 12/12 step COPY . /src 

What could be issue here ?

```
# cog.yaml 
# This file is used for constructing replicate env
image: "r8.im/tencentarc/realesrgan"

build:
  gpu: true
  python_version: "3.8"
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
  python_packages:
    - "torch"
    - "torchvision==0.8.2"
    - "numpy==1.21.1"
    - "lmdb==1.2.1"
    - "opencv-python==4.5.3.56"
    - "PyYAML==5.4.1"
    - "tqdm==4.62.2"
    - "yapf==0.31.0"
    - "basicsr==1.4.2"
    - "facexlib==0.2.5"


predict: "cog_predict.py:Predictor"
```

error on run 

```
docker run -it -p 5001:5000 --gpus all  cog-realesrgan-base 
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/predictor.py", line 57, in load_config
    with open(config_path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/src/cog.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/http.py", line 145, in <module>
    config = load_config()
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/predictor.py", line 60, in load_config
    raise ConfigDoesNotExist(
cog.errors.ConfigDoesNotExist: Could not find /src/cog.yaml
```

output from build 

```
Building Docker image from environment in cog.yaml as realsrgan...
[+] Building 13.7s (20/20) FINISHED                                                  
 => [internal] load build definition from Dockerfile                            0.0s
 => => transferring dockerfile: 2.17kB                                          0.0s
 => [internal] load .dockerignore                                               0.0s
 => => transferring context: 2B                                                 0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                    1.2s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab  0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubu  0.9s
 => [stage-0  1/12] FROM docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04  0.0s
 => [internal] load build context                                               0.0s
 => => transferring context: 82.97kB                                            0.0s
 => CACHED [stage-0  2/12] RUN rm -f /etc/apt/sources.list.d/cuda.list &&       0.0s
 => CACHED [stage-0  3/12] RUN --mount=type=cache,target=/var/cache/apt set -e  0.0s
 => CACHED [stage-0  4/12] RUN --mount=type=cache,target=/var/cache/apt apt-ge  0.0s
 => CACHED [stage-0  5/12] RUN curl -s -S -L https://raw.githubusercontent.com  0.0s
 => CACHED [stage-0  6/12] COPY .cog/tmp/build385192808/cog-0.0.1.dev-py3-none  0.0s
 => CACHED [stage-0  7/12] RUN --mount=type=cache,target=/root/.cache/pip pip   0.0s
 => CACHED [stage-0  8/12] RUN --mount=type=cache,target=/var/cache/apt apt-ge  0.0s
 => CACHED [stage-0  9/12] COPY .cog/tmp/build385192808/requirements.txt /tmp/  0.0s
 => CACHED [stage-0 10/12] RUN --mount=type=cache,target=/root/.cache/pip pip   0.0s
 => CACHED [stage-0 11/12] WORKDIR /src                                         0.0s
 => [stage-0 12/12] COPY . /src                                                 3.5s
 => exporting to image                                                          0.0s
 => => exporting layers                                                         0.0s
 => => writing image sha256:5d773d33193e12f3e0a998b79c86c37f3b6c9b7ddd64db3603  0.0s
 => => naming to docker.io/library/realsrgan                                    0.0s
 => exporting cache                                                             0.0s
 => => preparing build cache for export                                         0.0s
Adding labels to image...

Image built as realsrgan
```

**Comment by Tenfleques** [comment]
Asked bing chat and got some responses, however the command is failing with stat error for the host file

**Comment by Tenfleques** [comment]
Cleared docker cache. 
All works now.

**Comment by yigithanyucedag** [comment]
Same issue here
